---
language: python
python: "2.7"

sudo: required

services:
  - docker

addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  - pip install ansible-container

script:

  - COMPOSE_HTTP_TIMEOUT=360 ansible-container build

  - docker tag `basename $(pwd)`-build-tools rfhayashi/cljs-google-build-tools