- src: rfhayashi.openjdk
  version: '0.1'

- src: rfhayashi.lein
  version: '0.1'

- src: rfhayashi.nodejs
  version: '0.1'

- src: rfhayashi.rake
  version: '0.1'

- src: rfhayashi.gcloud
  version: '0.4'

- src: rfhayashi.docker-vagrant
  version: '0.1'

- src: rfhayashi.ansible-container
  version: '0.1'